### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by shabansamani** [maltloaf/prj-rev-bwfs-dasmoto#4]
**Grade:** Needs Improvement

**Summary:** While your code was pretty correct for the most part, minus those sub-heading tweaks you should make, the incorrect filepath to your CSS file essentially broke your site. It's those little things you need to watch out for sometimes. Don't be discouraged; just make the revisions you need and progress on in the course. Then when you learn newer concepts and ideas, be sure to revisit this project and add to it as further practice.

Also, be sure to check out this <a href="http://codeguide.co">code guide</a> to get an idea on how to write flexible, cohesive code. They include ideas like encoding your site with instructions to the browser and ensuring compatibility.

**Comment by maltloaf** [comment]
Many thanks for the feedback. I have corrected all the errors made and is all good now.
